# only run this if you need to setup for the first time, all other times just run `docker compose up -d`
# This script sets up the PostgreSQL database and creates the necessary tables and indexes.
# It also sets up the kafka topics and debezium connectors

docker compose up -d

echo -e "Waiting for services to start... (4s)\n"
sleep 4

# Create the db_updates topic
docker exec broker kafka-topics --create --if-not-exists \
  --topic db_updates \
  --partitions 3 \
  --replication-factor 1 \
  --bootstrap-server broker:29092

# Create the entities topic
docker exec broker kafka-topics --create --if-not-exists \
  --topic entities \
  --partitions 3 \
  --replication-factor 1 \
  --bootstrap-server broker:29092

# Create the possible_fraud topic (output of rps/src/service/llm.py)
docker exec broker kafka-topics --create --if-not-exists \
  --topic possible_fraud \
  --partitions 3 \
  --replication-factor 1 \
  --bootstrap-server broker:29092

docker exec broker kafka-topics --create --if-not-exists \
  --topic rps_processed_features \
  --partitions 3 \
  --replication-factor 1 \
  --bootstrap-server broker:29092

  # Create the postgres debezium topic
docker exec broker kafka-topics --create --if-not-exists \
  --topic postgres.public.toxicityhistory \
  --partitions 3 \
  --replication-factor 1 \
  --bootstrap-server broker:29092

docker exec broker kafka-topics --create --if-not-exists \
  --topic postgres.public.transactions \
  --partitions 3 \
  --replication-factor 1 \
  --bootstrap-server broker:29092

echo -e "Created topics. Now setting up the database tables...\n"
sleep 2

docker exec db_tuto_postgres psql -U "user" -d "values_db" -c "
DROP TABLE IF EXISTS Users CASCADE;
-- Corrected SQL for PostgreSQL
CREATE TABLE Users (
    user_id BIGINT PRIMARY KEY,
    uin CHAR(20),
    uin_hash CHAR(64),
    username VARCHAR(100),
    profile_pic TEXT, -- ADDED COLUMN
    email VARCHAR(255),
    phone VARCHAR(15),
    date_of_birth TIMESTAMP,
    address TEXT,
    occupation VARCHAR(200),
    annual_income DOUBLE PRECISION,
    
    -- Replaced MySQL ENUM with custom PostgreSQL type
    kyc_status VARCHAR(100),
    
    kyc_verified_at TIMESTAMP NULL,
    signature_hash VARCHAR(64),
    credit_score INT,
    blacklisted BOOLEAN DEFAULT FALSE,
    blacklisted_at TIMESTAMP NULL,
    current_rps_not DOUBLE PRECISION,
    current_rps_360 DOUBLE PRECISION,
    last_rps_calculation TIMESTAMP,
    
    -- Replaced MySQL ENUM with custom PostgreSQL type
    risk_category VARCHAR(100), 
    
    version INT DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time BIGINT, -- necessary acc to pw
    diff INT, -- necessary acc to pw

    -- Corrected: Removed MySQL-specific ON UPDATE. This functionality is handled by a TRIGGER.
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    
    -- Corrected: Replaced MySQL YEAR(CURDATE()) with PostgreSQL equivalent
    CONSTRAINT chk_age CHECK (
        EXTRACT(YEAR FROM AGE(date_of_birth)) >= 18
    ), 
    CONSTRAINT chk_credit_score CHECK (credit_score BETWEEN 300 AND 900)
);
"

docker exec db_tuto_postgres psql -U user -d values_db -c "
DROP TABLE IF EXISTS ToxicityHistory CASCADE;
CREATE TABLE ToxicityHistory (
    history_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    rps_not DOUBLE PRECISION,
    rps_360 DOUBLE PRECISION,
    sanction_score DOUBLE PRECISION,
    news_score DOUBLE PRECISION,
    transaction_score DOUBLE PRECISION,
    portfolio_score DOUBLE PRECISION,
    calculated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    calculation_trigger VARCHAR(50),
    time BIGINT, -- necessary acc to pw
    diff INT, -- necessary acc to pw
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- 2. Create the index
CREATE INDEX idx_user_timeline ON ToxicityHistory (user_id, calculated_at DESC);
"

docker exec db_tuto_postgres psql -U user -d values_db -c "
-- 1. Create the table with corrected syntax
DROP TABLE IF EXISTS UserSanctionMatches CASCADE;
CREATE TABLE UserSanctionMatches (
    match_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    match_found BOOLEAN ,
    match_confidence DOUBLE PRECISION,
    matched_entity_name VARCHAR(500),
    checked_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time BIGINT, -- necessary acc to pw
    diff INT, -- necessary acc to pw
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- 2. Create the index
CREATE INDEX idx_user_matches ON UserSanctionMatches (user_id, match_found);
"

docker exec db_tuto_postgres psql -U user -d values_db -c "
DROP TABLE IF EXISTS Staging_Buffer CASCADE;
CREATE TABLE Staging_Buffer (
    user_id BIGINT,
    uin CHAR(20),
    uin_hash CHAR(64),
    username TEXT,
    profile_pic TEXT, -- ADDED COLUMN
    email VARCHAR(255),
    phone VARCHAR(15),
    date_of_birth TIMESTAMP,
    address TEXT, -- CHANGED to TEXT
    occupation VARCHAR(200),
    annual_income DOUBLE PRECISION,
    kyc_status VARCHAR(100),
    kyc_verified_at TIMESTAMP,
    signature_hash VARCHAR(64),
    credit_score INT,
    blacklisted BOOLEAN DEFAULT FALSE,
    blacklisted_at TIMESTAMP,
    risk_category TEXT,
    current_rps_not DOUBLE PRECISION,
    current_rps_360 DOUBLE PRECISION,
    version INT DEFAULT 1,
    rps_not DOUBLE PRECISION,
    rps_360 DOUBLE PRECISION,
    sanction_score DOUBLE PRECISION,
    news_score DOUBLE PRECISION,
    transaction_score DOUBLE PRECISION,
    portfolio_score DOUBLE PRECISION,
    calculation_trigger VARCHAR(50),
    match_found BOOLEAN,
    match_confidence DOUBLE PRECISION,
    matched_entity_name TEXT,
    created_at TIMESTAMP,
    time BIGINT,
    diff INT
);
"

# 5. Create Trigger Function and Trigger (Semicolons fixed)
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE FUNCTION distribute_staging_data()
RETURNS TRIGGER AS \$\$
BEGIN
    -- Step A: Upsert into Users
    INSERT INTO Users (
        user_id, uin, uin_hash,
        username, profile_pic, email, phone, date_of_birth, -- Added profile_pic
        address, occupation, annual_income, kyc_status,
        kyc_verified_at, signature_hash, credit_score,
        blacklisted, blacklisted_at,
        current_rps_not, current_rps_360,
        risk_category, version,
        created_at, last_rps_calculation, time, diff, updated_at
    )
    VALUES (
        NEW.user_id, 
        NEW.uin, NEW.uin_hash,
        NEW.username, NEW.profile_pic, NEW.email, NEW.phone, NEW.date_of_birth, -- Added NEW.profile_pic
        NEW.address, NEW.occupation, NEW.annual_income, NEW.kyc_status,
        NEW.kyc_verified_at, NEW.signature_hash, NEW.credit_score,
        COALESCE(NEW.blacklisted, FALSE), NEW.blacklisted_at,
        NEW.current_rps_not, NEW.current_rps_360,
        NEW.risk_category, COALESCE(NEW.version, 1),
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), 
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), 
        NEW.time, NEW.diff,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (user_id) DO UPDATE SET
        username = COALESCE(NEW.username, Users.username),
        profile_pic = COALESCE(NEW.profile_pic, Users.profile_pic), -- Added update logic
        email = COALESCE(NEW.email, Users.email),
        phone = COALESCE(NEW.phone, Users.phone),
        date_of_birth = COALESCE(NEW.date_of_birth, Users.date_of_birth),
        address = COALESCE(NEW.address, Users.address),
        occupation = COALESCE(NEW.occupation, Users.occupation),
        annual_income = COALESCE(NEW.annual_income, Users.annual_income),
        kyc_status = COALESCE(NEW.kyc_status, Users.kyc_status),
        kyc_verified_at = COALESCE(NEW.kyc_verified_at, Users.kyc_verified_at),
        signature_hash = COALESCE(NEW.signature_hash, Users.signature_hash),
        credit_score = COALESCE(NEW.credit_score, Users.credit_score),
        blacklisted = COALESCE(NEW.blacklisted, Users.blacklisted),
        blacklisted_at = COALESCE(NEW.blacklisted_at, Users.blacklisted_at),
        current_rps_not = COALESCE(NEW.current_rps_not, Users.current_rps_not),
        current_rps_360 = COALESCE(NEW.current_rps_360, Users.current_rps_360),
        risk_category = COALESCE(NEW.risk_category, Users.risk_category),
        last_rps_calculation = COALESCE(NEW.created_at, Users.last_rps_calculation),
        updated_at = CURRENT_TIMESTAMP,
        version = Users.version + 1,
        time = COALESCE(NEW.time, Users.time),
        diff = COALESCE(NEW.diff, Users.diff);

    -- Step B: Insert into ToxicityHistory
    INSERT INTO ToxicityHistory (
        user_id, 
        rps_not, rps_360, sanction_score,   
        news_score, transaction_score, portfolio_score,
        calculation_trigger,
        calculated_at, time, diff
    )
    VALUES (
        NEW.user_id, 
        NEW.rps_not, NEW.rps_360, NEW.sanction_score, 
        NEW.news_score, NEW.transaction_score, NEW.portfolio_score,
        NEW.calculation_trigger,
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), NEW.time, NEW.diff
    );

    -- Step C: Insert into UserSanctionMatches
    INSERT INTO UserSanctionMatches (
        user_id, match_found, match_confidence, matched_entity_name, checked_at, time, diff
    )
    VALUES (
        NEW.user_id, NEW.match_found, NEW.match_confidence, NEW.matched_entity_name, 
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), NEW.time, NEW.diff
    );

    RETURN NEW;
END;
\$\$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_process_staging ON Staging_Buffer;
CREATE TRIGGER trigger_process_staging
AFTER INSERT ON Staging_Buffer
FOR EACH ROW
EXECUTE PROCEDURE distribute_staging_data();
"


docker exec db_tuto_postgres psql -U user -d values_db -c "
DROP TABLE IF EXISTS Transactions CASCADE;

CREATE TABLE Transactions (
    transaction_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    txn_timestamp TIMESTAMP,       -- Matches CSV header 'timestamp'
    amount DOUBLE PRECISION,
    currency VARCHAR(10),      -- e.g., 'USD'
    txn_type VARCHAR(50),      -- e.g., 'TRANSFER'
    counterparty_id BIGINT,
    is_fraud INT,              -- Matches '0' or '1' from CSV
    
    -- Foreign Key linkage
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- Index for time-based lookups
CREATE INDEX idx_txn_timestamp ON Transactions (user_id, timestamp DESC);
"


docker exec db_tuto_postgres psql -U user -d values_db -c "
-- =============================================================================
-- TABLE: compliance_alerts
-- PURPOSE: Security alerts, fraud notifications, and compliance warnings
-- =============================================================================
DROP TABLE IF EXISTS compliance_alerts CASCADE;
CREATE TABLE IF NOT EXISTS compliance_alerts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Foreign Keys
    user_id BIGINT,
    transaction_id BIGINT,

    -- Alert Classification
    alert_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'medium',
    title VARCHAR(255) NOT NULL,
    description TEXT,

    -- Alert Details
    entity_id VARCHAR(100),
    entity_type VARCHAR(50),
    rps360 DOUBLE PRECISION DEFAULT 0.0,

    -- Alert Status
    status VARCHAR(20) DEFAULT 'active',
    priority VARCHAR(20) DEFAULT 'medium',

    -- Dismissal & Acknowledgment
    is_acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_at TIMESTAMP WITHOUT TIME ZONE,
    acknowledged_by VARCHAR(100),
    dismissal_reason TEXT,

    -- Source & Context
    source VARCHAR(100),
    triggered_by VARCHAR(100),
    alert_metadata TEXT,

    -- Metadata
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time BIGINT, -- ADDED
    diff INT, -- ADDED

    -- Foreign Key Constraints
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE SET NULL,

    -- Check Constraints
    CHECK (alert_type IN ('kyc_alert', 'transaction_alert', 'fraud_alert', 'aml_alert', 'sanction_alert', 'behavioral_alert', 'system_alert')),
    CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CHECK (status IN ('active', 'investigating', 'resolved', 'dismissed', 'escalated')),
    CHECK (priority IN ('low', 'medium', 'high', 'critical'))
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_alerts_user_id ON compliance_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_transaction_id ON compliance_alerts(transaction_id);
CREATE INDEX IF NOT EXISTS idx_alerts_type ON compliance_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON compliance_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON compliance_alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON compliance_alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_acknowledged ON compliance_alerts(is_acknowledged);

-- Composite Indexes for Dashboard Queries
CREATE INDEX IF NOT EXISTS idx_alerts_severity_created ON compliance_alerts(severity DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_user_severity ON compliance_alerts(user_id, severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status_priority ON compliance_alerts(status, priority DESC);
"






#!/bin/bash

echo "Starting Superadmin Monitoring Schema setup..."

# =============================================================================
# 1. CREATE TABLES (One command per table)
# =============================================================================

echo "Creating core tables..."

# 1.1 CREATE admins (Reference/Bootstrap)
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE TABLE IF NOT EXISTS admins (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP WITH TIME ZONE,
    CHECK (role IN ('admin', 'superadmin'))
);
"

# 1.2 CREATE audit_logs
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    action_description TEXT NOT NULL,
    target_type VARCHAR(50),
    target_id INTEGER,
    target_identifier VARCHAR(255),
    action_metadata JSONB,
    ip_address VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
    CHECK (action_type IN (
        'classify_alert', 'dismiss_alert', 'escalate_alert',
        'blacklist_user', 'whitelist_user', 'flag_user', 'unflag_user',
        'block_transaction', 'approve_transaction', 'update_system_alert',
        'resolve_health_check', 'other'
    ))
);
"

# 1.3 CREATE system_metrics
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE TABLE IF NOT EXISTS system_metrics (
    id SERIAL PRIMARY KEY,
    metric_type VARCHAR(50) NOT NULL,
    metric_category VARCHAR(50) NOT NULL,
    metric_value FLOAT NOT NULL,
    metric_unit VARCHAR(20),
    time_window VARCHAR(20),
    aggregation_period_start TIMESTAMP WITH TIME ZONE,
    aggregation_period_end TIMESTAMP WITH TIME ZONE,
    details JSONB,
    total_count INTEGER,
    positive_count INTEGER,
    negative_count INTEGER,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_anomaly BOOLEAN DEFAULT FALSE,
    anomaly_threshold FLOAT,
    CHECK (metric_type IN (
        'alert_hit_rate', 'false_positive_rate', 'api_response_time',
        'api_error_rate', 'alert_response_time', 'user_flag_rate',
        'transaction_block_rate', 'other'
    )),
    CHECK (metric_category IN ('alert', 'api', 'transaction', 'user', 'system')),
    CHECK (metric_unit IN ('percentage', 'milliseconds', 'seconds', 'count', 'rate', 'ratio')),
    CHECK (time_window IN ('hourly', 'daily', 'weekly', 'monthly', 'realtime'))
);
"

# 1.4 CREATE system_health
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE TABLE IF NOT EXISTS system_health (
    id SERIAL PRIMARY KEY,
    check_type VARCHAR(50) NOT NULL,
    component_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    error_type VARCHAR(100),
    error_message TEXT,
    error_stacktrace TEXT,
    request_context JSONB,
    response_context JSONB,
    response_time_ms INTEGER,
    retry_count INTEGER DEFAULT 0,
    affected_operations JSONB,
    user_impact VARCHAR(20),
    is_resolved BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolution_notes TEXT,
    auto_recovered BOOLEAN DEFAULT FALSE,
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_occurrence TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    alert_sent BOOLEAN DEFAULT FALSE,
    alert_sent_at TIMESTAMP WITH TIME ZONE,
    alert_recipients JSONB,
    CHECK (check_type IN ('api_health', 'parser_health', 'db_health', 'service_health', 'network_health')),
    CHECK (status IN ('healthy', 'degraded', 'failed', 'recovering')),
    CHECK (severity IN ('info', 'warning', 'error', 'critical')),
    CHECK (user_impact IN ('none', 'low', 'medium', 'high', 'critical'))
);
"

# 1.5 CREATE system_alerts
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE TABLE IF NOT EXISTS system_alerts (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    severity VARCHAR(20) NOT NULL,
    component VARCHAR(100),
    metric_type VARCHAR(50),
    threshold_value VARCHAR(50),
    actual_value VARCHAR(50),
    alert_data JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolution_notes TEXT,
    triggered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    notifications_sent INTEGER DEFAULT 0,
    last_notification_at TIMESTAMP WITH TIME ZONE,
    CHECK (alert_type IN (
        'high_error_rate', 'api_downtime', 'anomaly_detected',
        'threshold_breach', 'health_check_failed', 'performance_degradation',
        'security_incident', 'other'
    )),
    CHECK (severity IN ('warning', 'error', 'critical')),
    CHECK (status IN ('active', 'acknowledged', 'resolved', 'false_alarm'))
);
"

echo "Creating Indexes..."

# =============================================================================
# 2. CREATE INDEXES (One command per table set of indexes)
# =============================================================================

# 2.1 Admins Indexes
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username);
CREATE INDEX IF NOT EXISTS idx_admins_email ON admins(email);
CREATE INDEX IF NOT EXISTS idx_admins_role ON admins(role);
"

# 2.2 Audit Logs Indexes
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_id ON audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action_type ON audit_logs(action_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_target_type ON audit_logs(target_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_target_id ON audit_logs(target_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action_metadata ON audit_logs USING GIN(action_metadata);
"

# 2.3 System Metrics Indexes
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE INDEX IF NOT EXISTS idx_system_metrics_type ON system_metrics(metric_type);
CREATE INDEX IF NOT EXISTS idx_system_metrics_category ON system_metrics(metric_category);
CREATE INDEX IF NOT EXISTS idx_system_metrics_recorded_at ON system_metrics(recorded_at);
CREATE INDEX IF NOT EXISTS idx_system_metrics_time_window ON system_metrics(time_window);
CREATE INDEX IF NOT EXISTS idx_system_metrics_is_anomaly ON system_metrics(is_anomaly);
CREATE INDEX IF NOT EXISTS idx_system_metrics_period_start ON system_metrics(aggregation_period_start);
CREATE INDEX IF NOT EXISTS idx_system_metrics_details ON system_metrics USING GIN(details);
"

# 2.4 System Health Indexes
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE INDEX IF NOT EXISTS idx_system_health_check_type ON system_health(check_type);
CREATE INDEX IF NOT EXISTS idx_system_health_component_name ON system_health(component_name);
CREATE INDEX IF NOT EXISTS idx_system_health_status ON system_health(status);
CREATE INDEX IF NOT EXISTS idx_system_health_severity ON system_health(severity);
CREATE INDEX IF NOT EXISTS idx_system_health_is_resolved ON system_health(is_resolved);
CREATE INDEX IF NOT EXISTS idx_system_health_detected_at ON system_health(detected_at);
CREATE INDEX IF NOT EXISTS idx_system_health_user_impact ON system_health(user_impact);
CREATE INDEX IF NOT EXISTS idx_system_health_request_context ON system_health USING GIN(request_context);
CREATE INDEX IF NOT EXISTS idx_system_health_response_context ON system_health USING GIN(response_context);
"

# 2.5 System Alerts Indexes
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE INDEX IF NOT EXISTS idx_system_alerts_alert_type ON system_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_system_alerts_severity ON system_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_system_alerts_status ON system_alerts(status);
CREATE INDEX IF NOT EXISTS idx_system_alerts_triggered_at ON system_alerts(triggered_at);
CREATE INDEX IF NOT EXISTS idx_system_alerts_component ON system_alerts(component);
CREATE INDEX IF NOT EXISTS idx_system_alerts_metric_type ON system_alerts(metric_type);
CREATE INDEX IF NOT EXISTS idx_system_alerts_alert_data ON system_alerts USING GIN(alert_data);
"

echo "Creating Views and Functions..."

# =============================================================================
# 3. CREATE VIEWS (One command per view)
# =============================================================================

# 3.1 View: Recent Audit Logs with Admin Details
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE VIEW v_audit_logs_with_admin AS
SELECT 
    al.*, a.username as admin_username, a.email as admin_email, a.role as admin_role
FROM audit_logs al
JOIN admins a ON al.admin_id = a.id
ORDER BY al.created_at DESC;
"

# 3.2 View: Active System Issues
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE VIEW v_active_system_issues AS
SELECT 
    'health_check' as issue_type, id, component_name as component, severity, error_message as description,
    detected_at as created_at, is_resolved
FROM system_health
WHERE is_resolved = FALSE AND severity IN ('error', 'critical')
UNION ALL
SELECT 
    'system_alert' as issue_type, id, component, severity, description,
    triggered_at as created_at, CASE WHEN status IN ('resolved', 'false_alarm') THEN TRUE ELSE FALSE END as is_resolved
FROM system_alerts
WHERE status IN ('active', 'acknowledged')
ORDER BY created_at DESC;
"

# 3.3 View: Metrics Summary (Last 24 Hours)
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE VIEW v_metrics_last_24h AS
SELECT 
    metric_type, metric_category, AVG(metric_value) as avg_value, MIN(metric_value) as min_value,
    MAX(metric_value) as max_value, COUNT(*) as data_points, SUM(CASE WHEN is_anomaly THEN 1 ELSE 0 END) as anomaly_count
FROM system_metrics
WHERE recorded_at >= NOW() - INTERVAL '24 hours'
GROUP BY metric_type, metric_category;
"

# =============================================================================
# 4. CREATE UTILITY FUNCTIONS (One command per function)
# =============================================================================

# 4.1 Function to calculate alert hit rate for a time period
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE FUNCTION calculate_alert_hit_rate(
    start_date TIMESTAMP WITH TIME ZONE, end_date TIMESTAMP WITH TIME ZONE
)
RETURNS FLOAT AS \$\$
DECLARE
    total_alerts INTEGER;
    true_positives INTEGER;
    hit_rate FLOAT;
BEGIN
    SELECT COUNT(*) INTO total_alerts FROM compliance_alerts
    WHERE created_at BETWEEN start_date AND end_date AND is_true_positive IS NOT NULL;
    
    SELECT COUNT(*) INTO true_positives FROM compliance_alerts
    WHERE created_at BETWEEN start_date AND end_date AND is_true_positive = TRUE;
    
    IF total_alerts > 0 THEN
        hit_rate := (true_positives::FLOAT / total_alerts::FLOAT) * 100;
    ELSE
        hit_rate := 0;
    END IF;
    RETURN hit_rate;
END;
\$\$ LANGUAGE plpgsql;
"

# 4.2 Function to get system health status
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE FUNCTION get_system_health_status()
RETURNS VARCHAR AS \$\$
DECLARE
    critical_count INTEGER;
    unresolved_errors INTEGER;
    health_status VARCHAR(20);
BEGIN
    SELECT COUNT(*) INTO critical_count FROM system_alerts
    WHERE status = 'active' AND severity = 'critical';
    
    SELECT COUNT(*) INTO unresolved_errors FROM system_health
    WHERE is_resolved = FALSE AND severity IN ('error', 'critical');
    
    IF critical_count > 0 THEN
        health_status := 'critical';
    ELSIF unresolved_errors > 0 THEN
        health_status := 'degraded';
    ELSE
        health_status := 'healthy';
    END IF;
    RETURN health_status;
END;
\$\$ LANGUAGE plpgsql;
"

# 4.3 Function to archive old audit logs
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE FUNCTION archive_old_audit_logs()
RETURNS INTEGER AS \$\$
DECLARE
    deleted_count INTEGER;
BEGIN
    WITH deleted AS (
        DELETE FROM audit_logs
        WHERE created_at < NOW() - INTERVAL '365 days'
        RETURNING *
    )
    SELECT COUNT(*) INTO deleted_count FROM deleted;
    RETURN deleted_count;
END;
\$\$ LANGUAGE plpgsql;
"

# 4.4 Function to clean up resolved health checks
docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE OR REPLACE FUNCTION cleanup_old_health_checks()
RETURNS INTEGER AS \$\$
DECLARE
    deleted_count INTEGER;
BEGIN
    WITH deleted AS (
        DELETE FROM system_health
        WHERE is_resolved = TRUE 
        AND resolved_at < NOW() - INTERVAL '30 days'
        RETURNING *
    )
    SELECT COUNT(*) INTO deleted_count FROM deleted;
    RETURN deleted_count;
END;
\$\$ LANGUAGE plpgsql;
"

# =============================================================================
# 5. COMMENTS (One command per comment)
# =============================================================================

docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON TABLE audit_logs IS 'Records all admin actions for compliance tracking';"
docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON TABLE system_metrics IS 'Stores system-wide performance metrics and KPIs';"
docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON TABLE system_health IS 'Tracks system health checks, failures, and recovery';"
docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON TABLE system_alerts IS 'System-level alerts for superadmin monitoring';"

docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON COLUMN audit_logs.action_metadata IS 'JSON containing before/after states, classification details, and additional context';"
docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON COLUMN system_metrics.details IS 'JSON containing metric breakdowns, distributions, and additional analysis';"
docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON COLUMN system_health.request_context IS 'JSON containing request details that triggered the health check';"
docker exec db_tuto_postgres psql -U user -d values_db -c "COMMENT ON COLUMN system_alerts.alert_data IS 'JSON containing alert-specific data and context';"

echo "Superadmin Monitoring Schema setup complete."



echo -e "Database tables set up. Now configuring Debezium connector...\n"
sleep 2

curl -X DELETE http://localhost:8083/connectors/values-connector
bash connector.sh 
