-- =============================================
-- Database Schema Migration
-- Updated Schema for Pathway Integration
-- Generated: December 5, 2025
-- =============================================

-- Drop existing tables if they exist (CASCADE to drop dependent objects)
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS ToxicityHistory CASCADE;
DROP TABLE IF EXISTS UserSanctionMatches CASCADE;
DROP TABLE IF EXISTS Staging_Buffer CASCADE;
DROP TABLE IF EXISTS Transactions CASCADE;

-- =============================================
-- Create Users Table
-- =============================================
CREATE TABLE Users (
    user_id BIGINT PRIMARY KEY,
    uin CHAR(20),
    uin_hash CHAR(64),
    username VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(15),
    date_of_birth TIMESTAMP,
    address TEXT,
    occupation VARCHAR(200),
    annual_income DOUBLE PRECISION,
    
    -- KYC Fields
    kyc_status VARCHAR(100),
    kyc_verified_at TIMESTAMP NULL,
    signature_hash VARCHAR(64),
    
    -- Credit & Risk Scoring
    credit_score INT,
    blacklisted BOOLEAN DEFAULT FALSE,
    blacklisted_at TIMESTAMP NULL,
    current_rps_not DOUBLE PRECISION,
    current_rps_360 DOUBLE PRECISION,
    last_rps_calculation TIMESTAMP,
    risk_category VARCHAR(100), 
    
    -- Version Control & Pathway Fields
    version INT DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time BIGINT, -- Pathway timestamp field
    diff INT,    -- Pathway diff field
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT chk_age CHECK (
        EXTRACT(YEAR FROM AGE(date_of_birth)) >= 18
    ), 
    CONSTRAINT chk_credit_score CHECK (credit_score BETWEEN 300 AND 900),
    CONSTRAINT chk_current_rps_not CHECK (current_rps_not IS NULL OR (current_rps_not >= 0 AND current_rps_not <= 1)),
    CONSTRAINT chk_current_rps_360 CHECK (current_rps_360 IS NULL OR (current_rps_360 >= 0 AND current_rps_360 <= 1))
);

-- =============================================
-- Create ToxicityHistory Table
-- =============================================
CREATE TABLE ToxicityHistory (
    history_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    
    -- Risk Scores
    rps_not DOUBLE PRECISION,
    rps_360 DOUBLE PRECISION,
    sanction_score DOUBLE PRECISION,
    news_score DOUBLE PRECISION,
    transaction_score DOUBLE PRECISION,
    portfolio_score DOUBLE PRECISION,
    
    -- Metadata
    calculated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    calculation_trigger VARCHAR(50),
    time BIGINT, -- Pathway timestamp field
    diff INT,    -- Pathway diff field
    
    -- Constraints
    CONSTRAINT chk_toxicity_rps_not CHECK (rps_not IS NULL OR (rps_not >= 0 AND rps_not <= 1)),
    CONSTRAINT chk_toxicity_rps_360 CHECK (rps_360 IS NULL OR (rps_360 >= 0 AND rps_360 <= 1)),
    
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- Create index for efficient user timeline queries
CREATE INDEX idx_user_timeline ON ToxicityHistory (user_id, calculated_at DESC);

-- =============================================
-- Create UserSanctionMatches Table
-- =============================================
CREATE TABLE UserSanctionMatches (
    match_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    
    -- Match Details
    match_found BOOLEAN,
    match_confidence DOUBLE PRECISION,
    matched_entity_name VARCHAR(500),
    
    -- Metadata
    checked_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time BIGINT, -- Pathway timestamp field
    diff INT,    -- Pathway diff field
    
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- Create index for efficient user match queries
CREATE INDEX idx_user_matches ON UserSanctionMatches (user_id, match_found);

-- =============================================
-- Create Staging_Buffer Table
-- =============================================
CREATE TABLE Staging_Buffer (
    user_id BIGINT,
    uin CHAR(20),
    uin_hash CHAR(64),
    username TEXT,
    email VARCHAR(255),
    phone VARCHAR(15),
    date_of_birth TIMESTAMP,
    address TEXT,
    occupation VARCHAR(200),
    annual_income DOUBLE PRECISION,
    kyc_status VARCHAR(100),
    kyc_verified_at TIMESTAMP,
    signature_hash VARCHAR(64),
    credit_score INT,
    blacklisted BOOLEAN DEFAULT FALSE,
    blacklisted_at TIMESTAMP,
    risk_category TEXT,
    current_rps_not DOUBLE PRECISION,
    current_rps_360 DOUBLE PRECISION,
    version INT DEFAULT 1,
    rps_not DOUBLE PRECISION,
    rps_360 DOUBLE PRECISION,
    sanction_score DOUBLE PRECISION,
    news_score DOUBLE PRECISION,
    transaction_score DOUBLE PRECISION,
    portfolio_score DOUBLE PRECISION,
    calculation_trigger VARCHAR(50),
    match_found BOOLEAN,
    match_confidence DOUBLE PRECISION,
    matched_entity_name TEXT,
    created_at TIMESTAMP,
    time BIGINT,
    diff INT
);

-- =============================================
-- Create Staging Buffer Distribution Function
-- =============================================
CREATE OR REPLACE FUNCTION distribute_staging_data()
RETURNS TRIGGER AS $$
BEGIN
    -- Step A: Upsert into Users
    INSERT INTO Users (
        user_id, uin, uin_hash,
        username, email, phone, date_of_birth,
        address, occupation, annual_income, kyc_status,
        kyc_verified_at, signature_hash, credit_score,
        blacklisted, blacklisted_at,
        current_rps_not, current_rps_360,
        risk_category, version,
        created_at, last_rps_calculation, time, diff, updated_at
    )
    VALUES (
        NEW.user_id, 
        NEW.uin, NEW.uin_hash,
        NEW.username, NEW.email, NEW.phone, NEW.date_of_birth,
        NEW.address, NEW.occupation, NEW.annual_income, NEW.kyc_status,
        NEW.kyc_verified_at, NEW.signature_hash, NEW.credit_score,
        COALESCE(NEW.blacklisted, FALSE), NEW.blacklisted_at,
        NEW.current_rps_not, NEW.current_rps_360,
        NEW.risk_category, COALESCE(NEW.version, 1),
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), 
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), 
        NEW.time, NEW.diff,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (user_id) DO UPDATE SET
        username = COALESCE(NEW.username, Users.username),
        email = COALESCE(NEW.email, Users.email),
        phone = COALESCE(NEW.phone, Users.phone),
        date_of_birth = COALESCE(NEW.date_of_birth, Users.date_of_birth),
        address = COALESCE(NEW.address, Users.address),
        occupation = COALESCE(NEW.occupation, Users.occupation),
        annual_income = COALESCE(NEW.annual_income, Users.annual_income),
        kyc_status = COALESCE(NEW.kyc_status, Users.kyc_status),
        kyc_verified_at = COALESCE(NEW.kyc_verified_at, Users.kyc_verified_at),
        signature_hash = COALESCE(NEW.signature_hash, Users.signature_hash),
        credit_score = COALESCE(NEW.credit_score, Users.credit_score),
        blacklisted = COALESCE(NEW.blacklisted, Users.blacklisted),
        blacklisted_at = COALESCE(NEW.blacklisted_at, Users.blacklisted_at),
        current_rps_not = COALESCE(NEW.current_rps_not, Users.current_rps_not),
        current_rps_360 = COALESCE(NEW.current_rps_360, Users.current_rps_360),
        risk_category = COALESCE(NEW.risk_category, Users.risk_category),
        last_rps_calculation = COALESCE(NEW.created_at, Users.last_rps_calculation),
        updated_at = CURRENT_TIMESTAMP,
        version = Users.version + 1,
        time = COALESCE(NEW.time, Users.time),
        diff = COALESCE(NEW.diff, Users.diff);

    -- Step B: Insert into ToxicityHistory
    INSERT INTO ToxicityHistory (
        user_id, 
        rps_not, rps_360, sanction_score,   
        news_score, transaction_score, portfolio_score,
        calculation_trigger,
        calculated_at, time, diff
    )
    VALUES (
        NEW.user_id, 
        NEW.rps_not, NEW.rps_360, NEW.sanction_score, 
        NEW.news_score, NEW.transaction_score, NEW.portfolio_score,
        NEW.calculation_trigger,
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), NEW.time, NEW.diff
    );

    -- Step C: Insert into UserSanctionMatches
    INSERT INTO UserSanctionMatches (
        user_id, match_found, match_confidence, matched_entity_name, checked_at, time, diff
    )
    VALUES (
        NEW.user_id, NEW.match_found, NEW.match_confidence, NEW.matched_entity_name, 
        COALESCE(NEW.created_at, CURRENT_TIMESTAMP), NEW.time, NEW.diff
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger on Staging_Buffer
DROP TRIGGER IF EXISTS trigger_process_staging ON Staging_Buffer;
CREATE TRIGGER trigger_process_staging
AFTER INSERT ON Staging_Buffer
FOR EACH ROW
EXECUTE PROCEDURE distribute_staging_data();

-- =============================================
-- Create Transactions Table (Aggregated Features)
-- =============================================
CREATE TABLE Transactions (
    -- Primary Key is now user_id (one record per user with aggregated features)
    user_id BIGINT PRIMARY KEY,
    
    -- User Context
    full_name VARCHAR(255) NOT NULL,
    
    -- 1-Hour Window Features
    total_amount_1h DOUBLE PRECISION NOT NULL,
    txn_count_1h INT NOT NULL,
    unique_cp_1h INT NOT NULL,           -- Unique Counterparties
    avg_amount_1h DOUBLE PRECISION NOT NULL,
    max_amount_1h DOUBLE PRECISION NOT NULL,
    min_amount_1h DOUBLE PRECISION NOT NULL,
    
    -- 24-Hour Window Features
    total_amount_24h DOUBLE PRECISION NOT NULL,
    txn_count_24h INT NOT NULL,
    unique_cp_24h INT NOT NULL,
    avg_amount_24h DOUBLE PRECISION NOT NULL,
    max_amount_24h DOUBLE PRECISION NOT NULL,
    min_amount_24h DOUBLE PRECISION NOT NULL,
    
    -- 7-Day Window Features
    total_amount_7d DOUBLE PRECISION NOT NULL,
    txn_count_7d INT NOT NULL,
    unique_cp_7d INT NOT NULL,
    avg_amount_7d DOUBLE PRECISION NOT NULL,
    max_amount_7d DOUBLE PRECISION NOT NULL,
    min_amount_7d DOUBLE PRECISION NOT NULL,
    
    -- 30-Day Window Features
    total_amount_30d DOUBLE PRECISION NOT NULL,
    txn_count_30d INT NOT NULL,
    unique_cp_30d INT NOT NULL,
    avg_amount_30d DOUBLE PRECISION NOT NULL,
    max_amount_30d DOUBLE PRECISION NOT NULL,
    min_amount_30d DOUBLE PRECISION NOT NULL,
    
    -- Ratio Feature
    incoming_outgoing_ratio_7d DOUBLE PRECISION NOT NULL,
    
    -- Audit Field
    calculated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign Key (Optional - uncomment if Users table integration is needed)
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

-- =============================================
-- End of Schema Migration
-- =============================================
