
docker exec db_tuto_postgres psql -U "user" -d "values_db" -c "
DROP TABLE IF EXISTS Users;
-- Corrected SQL for PostgreSQL
CREATE TABLE Users (
    user_id BIGINT PRIMARY KEY,
    aadhar_number CHAR(12) UNIQUE,
    aadhar_hash CHAR(64) UNIQUE,
    pan_number CHAR(10) UNIQUE,
    username VARCHAR(100),
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(15) UNIQUE,
    date_of_birth DATE,
    address_line1 VARCHAR(200),
    address_line2 VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode CHAR(6),
    occupation VARCHAR(200),
    annual_income DOUBLE PRECISION,
    
    -- Replaced MySQL ENUM with custom PostgreSQL type
    kyc_status VARCHAR(100),
    
    kyc_verified_at TIMESTAMP NULL,
    signature_hash VARCHAR(64),
    credit_score INT,
    blacklisted BOOLEAN DEFAULT FALSE,
    blacklisted_at TIMESTAMP NULL,
    blacklist_sync_id BIGINT,
    current_rps_not DOUBLE PRECISION,
    current_rps_360 DOUBLE PRECISION,
    last_rps_calculation TIMESTAMP,
    
    -- Replaced MySQL ENUM with custom PostgreSQL type
    risk_category VARCHAR(100), 
    
    version INT DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time BIGINT, -- necessary acc to pw
    diff INT, -- necessary acc to pw

    -- Corrected: Removed MySQL-specific ON UPDATE. This functionality is handled by a TRIGGER.
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    
    -- Corrected: Replaced MySQL YEAR(CURDATE()) with PostgreSQL equivalent
    CONSTRAINT chk_age CHECK (
        EXTRACT(YEAR FROM AGE(date_of_birth)) >= 18
    ), 
    CONSTRAINT chk_credit_score CHECK (credit_score BETWEEN 300 AND 900)
);
"

docker exec db_tuto_postgres psql -U user -d values_db -c "
CREATE TABLE ToxicityHistory (
    history_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    rps_not DOUBLE PRECISION,
    rps_360 DOUBLE PRECISION,
    sanction_score DOUBLE PRECISION,
    news_score DOUBLE PRECISION,
    transaction_score DOUBLE PRECISION,
    portfolio_score DOUBLE PRECISION,
    calculated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    calculation_trigger VARCHAR(50),
    time BIGINT, -- necessary acc to pw
    diff INT, -- necessary acc to pw
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- 2. Create the index
CREATE INDEX idx_user_timeline ON ToxicityHistory (user_id, calculated_at DESC);
"

docker exec db_tuto_postgres psql -U user -d values_db -c "
-- 1. Create the table with corrected syntax
CREATE TABLE UserSanctionMatches (
    match_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    match_found BOOLEAN NOT NULL,
    match_confidence DOUBLE PRECISION,
    matched_entity_name VARCHAR(500),
    checked_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time BIGINT, -- necessary acc to pw
    diff INT, -- necessary acc to pw
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- 2. Create the index
CREATE INDEX idx_user_matches ON UserSanctionMatches (user_id, match_found);
"